version: "3.8"

services:

  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: "crypto_db"
      POSTGRES_USER: "crypto_user"
      POSTGRES_PASSWORD: "crypto_pass"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  web:
    build: .
    volumes:
      - static_data:/app/static
    environment:
      DJANGO_SETTINGS_MODULE: "price_tracker.settings"
      SECRET_KEY: "django-insecure-change-me"
      DEBUG: "0"
      DB_NAME: "crypto_db"
      DB_USER: "crypto_user"
      DB_PASSWORD: "crypto_pass"
      DB_HOST: "db"
      DB_PORT: "5432"
      ALLOWED_HOSTS: "127.0.0.1, localhost"
    depends_on:
      - db
      - redis

  nginx:
    image: nginx:alpine
    ports:
      - "81:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_data:/usr/share/nginx/html/static:ro
    depends_on:
      - web

volumes:
  postgres_data:
  static_data:
